### ISSUE TITLE
XMAKB5R0P0A07 firmware

### ISSUE THREAD

**Issue by merinoffmike** [saltukkos/xiaomi-notebook-pro-bios-patcher#2]
Hi there. In the crave for everything fresh I accidentally flashed a new firmware XMAKB5R0P0A07. Do you think your tool will work with it? It loads the file and sorta kinda shows some normal values, but I'm really afraid to flash it.

EDIT: Well, actually it doesn't load, says the file is broken

**Comment by AlexeyMozgo** [comment]
Any news on this topic? I have BIOS 906 and the fans start working from 43 degrees. How to fix it?

**Comment by saltukkos** [comment]
Hi folks. Sorry for the long reply, but I abandoned the project since I don't own this laptop anymore. I will update the Readme file to clearly specify this.
